### ISSUE TITLE
Sending messages at programmatic speeds causes dropped messages on ganglion

### ISSUE THREAD

**Issue by andrewjaykeller** [OpenBCI/OpenBCI_Ganglion_Library#2]
Problem: Sending messages too fast one after the other can lead to earlier messages never being picked up. See https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion/issues/27

If a delay is introduced it seems to work https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion/tree/development

**Comment by biomurph** [comment]
Changed the BLE on receive function to use a ring buffer.

**Comment by andrewjaykeller** [comment]
nice @biomurph !
