### ISSUE TITLE
error in compiling GanglionWithSD

### ISSUE THREAD

**Issue by wliao229** [OpenBCI/OpenBCI_Ganglion_Library#3]
I got the following error when compiling `SD_Card_Stuff.ino` from Arduino, using  `OBCI_Ganglion_SD.h` from https://github.com/OpenBCI/OpenBCI_Ganglion_SD

```
/Volumes/Data/Documents/Arduino/libraries/OpenBCI_Ganglion_Library/examples/GanglionWithSD/SD_Card_Stuff.ino: In function 'boolean setupSDcard(char)':
SD_Card_Stuff:147: error: void value not ignored as it ought to be
   int numFiles = root.ls(0x00);
                              ^
exit status 1
void value not ignored as it ought to be
```

I have no problem of compiling `DefaultGanglion.ino`

**Comment by joelSensor** [comment]
What OS are you using? What version of Arduino?
Are you trying to compile SD_card_stuff.ino by itself?

**Comment by wliao229** [comment]
I am using macOS Sierra 10.12.3, Arduino 1.8.1.
I was not compiling SD_card_stuff.ino by itself. I was compiling GanglionWithSD.ino
I cloned the git and there is no problem compiling /examples/DefaultGanglion. 
![screen shot 2017-03-25 at 3 34 15 pm](https://cloud.githubusercontent.com/assets/6518201/24325516/d0bb06e4-1170-11e7-921b-c1d86e370da2.png)

**Comment by joelSensor** [comment]
Thanks for the info. That is a weird error. I have had problems, in the past, with passing '0x00' into a library function. I am not near my computer now, but try creating a variable before this line,

byte zero = 0x00;
Int numFiles = root.ls(zero);

I will try on my system when I can and get back to you

**Comment by wliao229** [comment]
This doesn’t help. The same error remains. I’m not savvy in C++, but I notice in `OpenBCI_Ganglion_SD/OBCI_Ganglion_SD/utility/SdFile.cpp`, 

```
//------------------------------------------------------------------------------
/** List directory contents to Serial.
 *
 * \param[in] flags The inclusive OR of
 *
 * LS_DATE - %Print file modification date
 *
 * LS_SIZE - %Print file size.
 *
 * LS_R - Recursive list of subdirectories.
 *
 * \param[in] indent Amount of space before file name. Used for recursive
 * list to indicate subdirectory level.
 */
void SdFile::ls(uint8_t flags, uint8_t indent) {
...
```

The ls() does not return anything. Would this be the problem in `int numFiles = root.ls(zero);` ?



 the SDFile::ls

**Comment by abek42** [comment]
Hi,

Did you create a fix for this?

From reading the code, the SdFile::ls function returns a void, so the initialization of numFiles is not possible directly.

For our project, SD writing by the Ganglion is a critical step, so any help is appreciated.

We have an alternative function which can initialize numFiles properly, but we are worried about bricking the board by uploading a non-compliant version.

Thanks.
Abe

**Comment by biomurph** [comment]
I just made the change. the ls function now will return the number of files on the root.
The SD card writing will create some noise, unfortunately. This is due to the fact that max SPI SCLK frequency is 4MHz on the Simblee. This problem is still looking for a fix.

**Comment by abek42** [comment]
Thanks for this. 
Are you saying that if the Ganglion is writing to the SD card, the electrodes will pick up noise due to this process? If so, do you have any data on what the SNR is?

**Comment by biomurph** [comment]
The noise is not 'very' large, but it does show up on the FFT across many frequencies.
